weights: ''
cfg: /home/nguyen.thanh.huyenb/yolov7/yolov7_train/cfg/training/yolov7.yaml
data: /home/nguyen.thanh.huyenb/yolov7/yolov7_train/data/coco.yaml
hyp: /home/nguyen.thanh.huyenb/yolov7/yolov7_train/data/hyp.scratch.p5.yaml
epochs: 300
batch_size: 4
img_size:
- 320
- 320
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: test-scale
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
world_size: 1
global_rank: -1
save_dir: runs/train/test-scale3
total_batch_size: 4
